[package]
name = "sdtx"
version = "0.1.3"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.28"
nix = "0.26.2"
smallvec = "1.10.0"
thiserror = "1.0.40"
tracing = "0.1.37"
