[package]
name = "sdtx"
version = "0.1.5"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.30"
nix = { version = "0.29.0", features = ["ioctl"] }
smallvec = "1.13.2"
thiserror = "1.0.63"
tracing = "0.1.40"
