[package]
name = "sdtx"
version = "0.1.4"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.28"
nix = { version = "0.27.1", features = ["ioctl"] }
smallvec = "1.11.1"
thiserror = "1.0.49"
tracing = "0.1.37"
