[package]
name = "sdtx"
version = "0.1.2"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.13"
nix = "0.20.0"
smallvec = "1.6.1"
thiserror = "1.0.24"
tracing = "0.1.25"
