[package]
name = "sdtx"
version = "0.1.5"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.31"
nix = { version = "0.29.0", features = ["ioctl"] }
smallvec = "1.15.0"
thiserror = "2.0.12"
tracing = "0.1.41"
