[package]
name = "sdtx"
version = "0.1.4"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.30"
nix = { version = "0.28.0", features = ["ioctl"] }
smallvec = "1.13.1"
thiserror = "1.0.58"
tracing = "0.1.40"
