[package]
name = "sdtx"
version = "0.1.3"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
nix = "0.24.1"
smallvec = "1.8.0"
thiserror = "1.0.30"
tracing = "0.1.34"
