[package]
name = "sdtx-tokio"
version = "0.1.2"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
sdtx = { path = "../sdtx", version = "0.1" }
tokio = { version = "1.18.0", features = ["fs", "io-util"] }
