[package]
name = "sdtx-tokio"
version = "0.1.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.13"
sdtx = { path = "../sdtx" }
tokio = { version = "1.4.0", features = ["fs", "io-util"] }
