[package]
name = "sdtx-tokio"
version = "0.1.4"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.30"
sdtx = { path = "../sdtx", version = "0.1.5" }
tokio = { version = "1.40.0", features = ["fs", "io-util"] }
