[package]
name = "sdtx-tokio"
version = "0.1.4"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.28"
sdtx = { path = "../sdtx", version = "0.1.4" }
tokio = { version = "1.32.0", features = ["fs", "io-util"] }
